x-aws-vpc: "vpc-caef7fa1"
services:
  web:
    image: dhirajbansal43/java-web-app:latest
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
          AWS_DEFAULT_REGION: "us-east-2"
